#!/bin/bash

version=0.0.2

real_grep=$(which -a grep | tail -1 | awk '{ print $1 }')

usage()
{
cat << EOF

    Usage: $0 [options] [path]

    List the node modules and their versions for a given path (defaulting to
    the current working directory).

    OPTIONS:

      -h    Show this message
      -V    Show version
      -j    Format the output as a JSON snippet for inclusion in a package.json
            file
      -p    Check all parent directories back to the root for available modules

EOF
}

pkg_format="%s@%s"
output_format="\n%s"
trailing_comma=0

check_parent_dirs=

while getopts "hVjp" option
do
    case $option in
        h)
            usage
            exit 1
            ;;
        V)
            echo "version $version"
            exit 1
            ;;
        j)
            pkg_format='"%s": "%s"'
            output_format="\n%s,"
            trailing_comma=1
            shift
            ;;
        p)
            check_parent_dirs=1
            shift
            ;;
        ?)
            usage
            exit 2
            ;;
    esac
done

find_base_path=${1:-.}
abs_find_base_path=$(cd $find_base_path; pwd)

build_package_file_list()
{
    files=${1:-}
    modules_dir="$2/node_modules"

    if [ -d $modules_dir ]
    then
        files=$(echo "$files" && find $modules_dir -maxdepth 2 -name "package.json")
    fi

    if [ $check_parent_dirs ]
    then
        if [ '/' != $2 ]
        then
            parent_dir=$(dirname $2)
            build_package_file_list "$files" $parent_dir
        else
            echo "$files"
        fi
    else
        echo "$files"
    fi
}

pkg_files=$(build_package_file_list '' $abs_find_base_path)
declare -a modules

for f in $pkg_files
do
    mod=$(basename $(dirname $f))
    ver=$($real_grep -e '"version"\s*:\s*' $f | $real_grep -v "readme" | sed 's/^.*"version"[^:]*:[^"]*"\([^"]\{1,\}\)".*$/\1/')


    printf -v str "$pkg_format" "$mod" "$ver"
    modules=("${modules[@]}" "$str")
done

output="$( printf "$output_format" "${modules[@]}" | sort )"
len="$(( ${#output} - 1 - $trailing_comma ))"

echo "${output:1:$len}"
